services:
  - type: web
    name: nyp-tech-portfolio
    runtime: node
    buildCommand: npm install
    startCommand: npm start
    env: node
    staticPublishPath: ./public
    envVars:
      - key: NODE_ENV
        value: production